server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:4677/raji
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate.ddl-auto: update
